refactor(pre-push): update script path to use subdirectory

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 echo "Building debug build..."
-./xcbuild-debug.sh
+./scripts/xcbuild-debug.sh
 
 if [ $? -ne 0 ]; then
-    echo "❌ Build failed."
-    exit 1
+	echo "❌ Build failed."
+	exit 1
 fi
 
 echo "✅ Build completed successfully."
