refactor: update pre-commit hook to run SwiftFormat and adjust FindView layout

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+echo "🎨 Running SwiftFormat..."
+if ! command -v swiftformat >/dev/null 2>&1; then
+    echo "⚠️ SwiftFormat not installed. Install with 'brew install swiftformat' or execute './setup.sh.'"
+    exit 1
+fi
+swiftformat . --quiet
+if [ $? -ne 0 ]; then
+    echo "❌ SwiftFormat failed."
+    exit 1
+fi
+
 echo "🔍 Running SwiftLint..."
 if ! command -v swiftlint >/dev/null 2>&1; then
     echo "⚠️ SwiftLint not installed. Install with 'brew install swiftlint' or execute './setup.sh.'"
@@ -11,16 +22,6 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-echo "🎨 Running SwiftFormat..."
-if ! command -v swiftformat >/dev/null 2>&1; then
-    echo "⚠️ SwiftFormat not installed. Install with 'brew install swiftformat' or execute './setup.sh.'"
-    exit 1
-fi
-swiftformat .
-if [ $? -ne 0 ]; then
-    echo "❌ SwiftFormat failed."
-    exit 1
-fi
 git add .
 
 echo "✅ Pre-commit checks passed!"
